Testing Git Hook, file change

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,23 +1,34 @@
-#!/bin/bash
+#!/bin/sh
+echo "Running golint for staged go file"
 
-echo "Test Hook"
+STAGED_GO_FILES=$(git diff --cached --name-only | grep "\.go$")
 
-# this will retrieve all of the .go files that have been 
-# changed since the last commit
-STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')
+if [[ "$STAGED_GO_FILES" = "" ]]; then
+  echo No staged go file
+fi
 
-# we can check to see if this is empty
-if [[ $STAGED_GO_FILES == "" ]]; then
-    echo "No Go Files to Update"
-# otherwise we can do stuff with these changed go files
+PASS=
+
+for FILE in $STAGED_GO_FILES
+do 
+  errorCount=$(go run golang.org/x/lint/golint $STAGED_GO_FILES | wc -l)
+  if [ "$errorCount" -gt '0' ]; then
+    printf "\t\033[31mgolint $FILE\033[0m \033[0;30m\033[41mFAIL\033[0m\n"
+      
+    echo $errCount
+    echo "suggestions for: $FILE"
+    go run golang.org/x/lint/golint $FILE
+    PASS=false
+  else  
+    printf "\t\033[32mgolint $FILE\033[0m \033[0;30m\033[42mPASS\033[0m\n"
+    PASS=true
+  fi
+done
+
+if ! $PASS; then
+  printf "\033[0;30m\033[41mCOMMIT FAILED !!!!\033[0m\n"
+  exit 1
 else
-    for file in $STAGED_GO_FILES; do
-    
-        echo $file
-
-        golint "-set_exit_status" $FILE
-        if [[ $? == 1 ]]; then
-        PASS=false
-        fi
-    done
+  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
+  exit 0
 fi
